@echo off
echo Descargando archivo ZIP...
curl -o "%TEMP%\VisionexWave.zip" "https://github.com/Nisamov/VisionexWave/archive/master.zip"
echo Descomprimiendo archivo ZIP...
7z x -o"%TEMP%" "%TEMP%\VisionexWave.zip"
echo Ejecutando el instalador...
start /wait setup.exe